const key = 'containers.ForgotPassword';

const SHOW_FORGOT_PASSWORD_MODAL = `${key}.SHOW_FORGOT_PASSWORD_MODAL`;
const HIDE_FORGOT_PASSWORD_MODAL = `${key}.HIDE_FORGOT_PASSWORD_MODAL`;

const GET_VERIFICATION_CODE = `${key}.GET_VERIFICATION_CODE`;
const GET_VERIFICATION_CODE_SUCCESS = `${key}.GET_VERIFICATION_CODE_SUCCESS`;
const GET_VERIFICATION_CODE_ERROR = `${key}.GET_VERIFICATION_CODE_ERROR`;

const SET_NEW_PASSWORD = `${key}.SET_NEW_PASSWORD`;
const SET_NEW_PASSWORD_SUCCESS = `${key}.SET_NEW_PASSWORD_SUCCESS`;
const SET_NEW_PASSWORD_ERROR = `${key}.SET_NEW_PASSWORD_ERROR`;

// Modals
const GET_VERIFICATION_CODE_MODAL = `${key}.GET_VERIFICATION_CODE_MODAL`;
const SET_NEW_PASSWORD_MODAL = `${key}.SET_NEW_PASSWORD_MODAL`;
const SUCCESS_BANNER = `${key}.SUCCESS_BANNER`;

export {
  SHOW_FORGOT_PASSWORD_MODAL,
  HIDE_FORGOT_PASSWORD_MODAL,
  GET_VERIFICATION_CODE,
  GET_VERIFICATION_CODE_SUCCESS,
  GET_VERIFICATION_CODE_ERROR,
  GET_VERIFICATION_CODE_MODAL,
  SUCCESS_BANNER,
  SET_NEW_PASSWORD_MODAL,
  SET_NEW_PASSWORD,
  SET_NEW_PASSWORD_SUCCESS,
  SET_NEW_PASSWORD_ERROR,
};
