const key = 'containers.Products';

const GET_USER_PRODUCTS = `${key}.GET_USER_PRODUCTS`;
const GET_USER_PRODUCTS_SUCCESS = `${key}.GET_USER_PRODUCTS_SUCCESS`;
const GET_USER_PRODUCTS_ERROR = `${key}.GET_USER_PRODUCTS_ERROR`;

const START_TRACKING = `${key}.START_TRACKING`;
const START_TRACKING_SUCCESS = `${key}.START_TRACKING_SUCCESS`;
const START_TRACKING_ERROR = `${key}.START_TRACKING_ERROR`;

const FINISH_TRACKING = `${key}.FINISH_TRACKING`;
const FINISH_TRACKING_SUCCESS = `${key}.FINISH_TRACKING_SUCCESS`;
const FINISH_TRACKING_ERROR = `${key}.FINISH_TRACKING_ERROR`;

const GET_STAT = `${key}.GET_STAT`;
const GET_STAT_SUCCESS = `${key}.GET_STAT_SUCCESS`;
const GET_STAT_ERROR = `${key}.GET_STAT_ERROR`;

const SHOW_PRODUCT_INFO_MODAL = `${key}.SHOW_PRODUCT_INFO_MODAL`;
const HIDE_PRODUCT_INFO_MODAL = `${key}.HIDE_PRODUCT_INFO_MODAL`;

export {
  GET_USER_PRODUCTS,
  GET_USER_PRODUCTS_SUCCESS,
  GET_USER_PRODUCTS_ERROR,
  START_TRACKING,
  START_TRACKING_SUCCESS,
  START_TRACKING_ERROR,
  FINISH_TRACKING,
  FINISH_TRACKING_SUCCESS,
  FINISH_TRACKING_ERROR,
  GET_STAT,
  GET_STAT_SUCCESS,
  GET_STAT_ERROR,
  SHOW_PRODUCT_INFO_MODAL,
  HIDE_PRODUCT_INFO_MODAL,
};
