const key = 'containers.GlobalProvider';

const GET_CURRENT_USER = `${key}.GET_CURRENT_USER`;
const GET_CURRENT_USER_SUCCESS = `${key}.GET_CURRENT_USER_SUCCESS`;
const GET_CURRENT_USER_ERROR = `${key}.GET_CURRENT_USER_ERROR`;

const CHANGE_USER_LOCALE = `${key}.CHANGE_USER_LOCALE`;
const CHANGE_USER_LOCALE_SUCCESS = `${key}.CHANGE_USER_LOCALE_SUCCESS`;
const CHANGE_USER_LOCALE_ERROR = `${key}.CHANGE_USER_LOCALE_ERROR`;

export {
  GET_CURRENT_USER,
  GET_CURRENT_USER_SUCCESS,
  GET_CURRENT_USER_ERROR,
  CHANGE_USER_LOCALE,
  CHANGE_USER_LOCALE_SUCCESS,
  CHANGE_USER_LOCALE_ERROR,
};
