const key = 'containers.ChangePassword';

const SHOW_CHANGE_PASSWORD_MODAL = `${key}.SHOW_CHANGE_PASSWORD_MODAL`;
const HIDE_CHANGE_PASSWORD_MODAL = `${key}.HIDE_CHANGE_PASSWORD_MODAL`;

const CHANGE_PASSWORD = `${key}.CHANGE_PASSWORD`;
const CHANGE_PASSWORD_SUCCESS = `${key}.CHANGE_PASSWORD_SUCCESS`;
const CHANGE_PASSWORD_ERROR = `${key}.CHANGE_PASSWORD_ERROR`;

export {
  SHOW_CHANGE_PASSWORD_MODAL,
  HIDE_CHANGE_PASSWORD_MODAL,
  CHANGE_PASSWORD,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_ERROR,
};
